services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: starship
      POSTGRES_USER: starship
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
