services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

  bot-dev:
    build:
      context: .
      target: builder
    command: npm run start:dev
    env_file:
      - .env
    volumes:
      - ./:/app # чтобы видеть правки на лету
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: starship
      POSTGRES_USER: starship
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
